main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('accounts/signup/', views.signup, name='signup'),
    path('accounts/signup/vintner', views.VintnerSignUpView.as_view(), name='vintner_signup'),
    path('accounts/signup/enthusiast', views.EnthusiastSignUpView.as_view(), name='enthusiast_signup'),
    path('glossary/', views.glossary, name='glossary'),
    path('profile/', views.profile, name='profile'),

    ### Winery ###
    path('findwineries/', views.find_wineries, name='find_wineries'),
    path('winery/create/', views.create_winery, name='winery_create'),
    path('winery/<int:winery_id>', views.winery_detail, name="winery_detail"),
    path('winery/<int:winery_id>/update/', views.winery_update, name='winery_update'),
    path('winery/<int:pk>/delete/', views.WineryDelete.as_view(), name='winery_delete'),
    path('winery/search', views.winery_search, name="winery_search"),
    ### Wines ###
    path('findwines/', views.home, name='home'),
    path('mywines/', views.my_wines, name='my_wines'),
    path('wine/<int:pk>/', views.WineDetail.as_view(), name='wine_detail'),
    path('winery/<int:winery_id>/add_wine/', views.create_wine, name='add_wine'),
    path('wine/<int:wine_id>/update/', views.wine_update, name='wine_update'),
    path('wine/<int:pk>/delete/', views.WineDelete.as_view(), name='wine_delete'),
    path('wine/search', views.wine_search, name="wine_search"),
    path('wine/mapsearch', views.wine_search_map, name="wine_search_map"),
    ### Grapes ###
    path('mygrapes/', views.my_grapes, name='my_grapes'),
    ### Comments ###
    path('wine/<int:wine_id>/add_comment/', views.create_comment, name='add_comment'),
    path('comment/<int:pk>/update/', views.CommentUpdate.as_view(), name='comment_update'),
    path('comment/<int:pk>/delete/', views.CommentDelete.as_view(), name='comment_delete'),
]

mysomm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import  AbstractUser

from django.urls import reverse


class User(AbstractUser):
    is_vintner = models.BooleanField(default=False)
    is_enthusiast = models.BooleanField(default=False)

class Vintner(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

class Enthusiast(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)




class County(models.Model):
    name = models.CharField(max_length=100)
    state = models.CharField(max_length=2)
    lat = models.DecimalField(max_digits=9, decimal_places=6)
    lon = models.DecimalField(max_digits=9, decimal_places=6)

    def __str__(self):
        return f'{self.name} is in {self.state}'

# Create your models here.
class Winery(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    region = models.CharField(max_length=100)
    county = models.ForeignKey(County, on_delete=models.SET_NULL, null=True)
    city = models.CharField(max_length=100)
    zipcode = models.CharField(max_length=5, null=True)
    img_url = models.CharField(max_length=100, null=True)
    logo_url = models.CharField(max_length=100, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} is located at {self.address} in {self.city}.'
    

class Wine(models.Model):
    RED = 'RD'
    WHITE = 'WH'
    ROSE = 'RS'
    COLOR_CHOICES = [
        ('', 'Color'), ## Allows for blanks in search and dropdowns
        (RED, 'Red'),
        (WHITE, 'White'),
        (ROSE, 'Rosé'),
    ]

    name = models.CharField(max_length=100)
    style = models.CharField(max_length=100, null=True)
    grape = models.CharField(max_length=100, null=True)
    vintage = models.CharField(max_length=4, null=True)
    color = models.CharField(max_length=5, choices=COLOR_CHOICES, default=RED, null=True)
    taste_notes = models.TextField(max_length=250, null=True)
    image_url = models.CharField(max_length=100, null=True)
    winery = models.ForeignKey(Winery, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} is a {self.vintage} {self.style} wine.'

    def get_absolute_url(self):
        return reverse('winery_detail', kwargs={'winery_id': self.winery.id})


# Grape Model for Future Expansion    
class Grape(models.Model):
    name = models.CharField(max_length=100)
    sci_name = models.CharField(max_length=100)
    image_url = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.name} has a scientific name of {self.sci_name}'

class Comment(models.Model):
    
    SCORES = [
        ('1','1'),
        ('2','2'),
        ('3','3'),
        ('4','4'),
        ('5','5'),
    ]

    content = models.TextField(max_length=250, null=True)
    rating = models.TextField(choices=SCORES, default=SCORES[0][0])
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    wine = models.ForeignKey(Wine, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.rating} is the rating on this comment'
    
    def get_absolute_url(self):
        return reverse('wine_detail', args={self.wine.id})

main_app/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView, TemplateView, FormView, DeleteView
from .models import Winery, Wine, Grape
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from . import map_us
from .models import Wine, County, Comment
from .forms import WineryForm, WineForm, WineSearchForm, WinerySearchForm, VintnerSignUpForm, EnthusiastSignUpForm, CommentForm

User = get_user_model()

# Create your views here.


def home(request, **kwargs):
  selected_wines = Wine.objects.all()
  wine_query =  []
  for county in County.objects.all():
    county_wines = selected_wines.filter(winery__county = county)
    if len(county_wines) > 0:
      wine_query.append({
        "name": county.name,
        "state": county.state,
        "lat": county.lat,
        "lon": county.lon,
        "count": len(county_wines),
        "county_id": county.id
      })
  map_data= map_us.render_map(wine_query)
  wine_search_form = WineSearchForm(auto_id='id_%s_wine')
  winery_search_form = WinerySearchForm(auto_id='id_%s_winery')
  return render(request, 'index.html', context= {
    "selected_wines": selected_wines,
    "plot": map_data,
    "wine_form": wine_search_form,
    "winery_form": winery_search_form,
    })




@login_required
def profile(request):
  my_wineries = Winery.objects.filter(user=request.user.id)

  return render(request, 'profile.html', {'my_wineries': my_wineries})



@login_required
def glossary(request):
  return render(request, 'glossary.html')



def about(request):
  return render(request, 'about.html')





######### WINERY ########


def find_wineries(request):
  return render(request, 'winery/index.html')



@login_required
def create_winery(request):
  if request.method == 'POST':
    form = WineryForm(request.POST)
    if form.is_valid():
      input_county = form.cleaned_data['county']
      input_state = form.cleaned_data['state']
      try: 
        db_county = County.objects.get(name__iexact=input_county, state__iexact=input_state)
      except:
        error = "County not found. Please try again."
        return render(request, 'main_app/winery_form.html', {"form": form, "error": error})
      winery = Winery(
        name = form.cleaned_data['name'],
        address = form.cleaned_data['address'],
        region = form.cleaned_data['region'],
        county = db_county,
        city = form.cleaned_data['city'],
        zipcode = form.cleaned_data['zipcode'],
        img_url = form.cleaned_data['img_url'],
        logo_url = form.cleaned_data['logo_url'],
        user = request.user
      )
      winery.save()
      return redirect('winery_detail', winery_id=winery.id)
  form = WineryForm()
  return render(request, 'main_app/winery_form.html', {"form": form})

def winery_detail(request, winery_id):
  try:
    winery = Winery.objects.get(id=winery_id)
  except:
    return redirect('profile')
  wine_form = WineForm()
  return render(request, 'winery/detail.html', {"winery": winery, "wine_form": wine_form})



@login_required
def winery_update(request, winery_id):
  winery = Winery.objects.get(pk=winery_id)
  if request.method == 'POST':
    form = WineryForm(request.POST)
    if form.is_valid():
      input_county = form.cleaned_data['county']
      input_state = form.cleaned_data['state']
      try: 
        db_county = County.objects.get(name__iexact=input_county, state__iexact=input_state)
      except:
        error = "County not found. Please try again."
        return render(request, 'main_app/winery_form.html', {"form": form, "error": error})
      winery.name = form.cleaned_data['name']
      winery.address = form.cleaned_data['address']
      winery.region = form.cleaned_data['region']
      winery.county = db_county
      winery.city = form.cleaned_data['city']
      winery.zipcode = form.cleaned_data['zipcode']
      winery.img_url = form.cleaned_data['img_url']
      winery.logo_url = form.cleaned_data['logo_url']
      winery.user = request.user
      winery.save()
      return redirect('winery_detail', winery_id=winery.id)
  form = WineryForm(initial={
    'name': winery.name,
    'address': winery.address,
    'region': winery.region,
    'county': winery.county.name,
    'city': winery.city,
    'state': winery.county.state,
    'zipcode': winery.zipcode,
    'img_url': winery.img_url,
    'logo_url': winery.logo_url
    })
  return render(request, 'main_app/winery_form.html', {"form": form, "winery": winery})



class WineryDelete(LoginRequiredMixin, DeleteView):
  model = Winery
  success_url = '/profile/'


def winery_search(request):
  if request.is_ajax() and request.method == "GET":
    filter_terms = {}
    location = {}
    for item in request.GET.items():
      if item[1] != "" and item[0] != 'csrfmiddlewaretoken':
        if item[0] == "county":
          location['county'] = item[1]
        elif item[0] == "state":
          location['state'] = item[1]
        else:
          query = item[0] + "__icontains"
          filter_terms[query] = item[1]
    if len(location) == 2:
      try:
        county = County.objects.get(name__iexact=location['county'], state__iexact=location['state'])
        filter_terms['county'] = county.id
      except:
        pass
    wineries = Winery.objects.filter(**filter_terms)[:10].values('name', 'region', 'county', 'id')
    winery_results = list(wineries)
    for winery in winery_results:
      dbcounty = County.objects.get(pk=winery['county'])
      winery['county'] = dbcounty.name
      winery['state'] = dbcounty.state
    return JsonResponse(winery_results,safe=False)
  return JsonResponse({}, status=400)

######### WINES #########
@login_required
def my_wines(request):
  wines = Wine.objects.filter(winery__user=request.user)
  return render(request, 'wines/my_wines.html', {
    "my_wines": wines,
  })


@login_required
def create_wine(request, winery_id):
  form = WineForm(request.POST)
  if form.is_valid():
    new_wine = form.save(commit=False)
    new_wine.winery_id = winery_id
    new_wine.save()
  return redirect('winery_detail', winery_id=winery_id)
  

class WineDetail(LoginRequiredMixin, DetailView):
  model = Wine
  def get_context_data(self, **kwargs):
        context = super(WineDetail, self).get_context_data(**kwargs)
        context['comment_form'] = CommentForm()
        context['quini_token'] = 'ujm3rn9xivc2ulzyjh82'
        return context


@login_required
def wine_update(request, wine_id):
  wine = Wine.objects.get(pk=wine_id)
  if request.method == 'POST':
    form = WineForm(request.POST)
    if form.is_valid():
      wine.name = form.cleaned_data['name']
      wine.style = form.cleaned_data['style']
      wine.grape = form.cleaned_data['grape']
      wine.color = form.cleaned_data['color']
      wine.taste_notes = form.cleaned_data['taste_notes']
      wine.image_url = form.cleaned_data['image_url']
      wine.save()
      return redirect('wine_detail', pk=wine_id)
  form = WineForm(initial={
    'name': wine.name,
    'style': wine.style,
    'grape': wine.grape,
    'color': wine.color,
    'taste_notes': wine.taste_notes,
    'image_url': wine.image_url,
    })
  return render(request, 'main_app/wine_form.html', {"wine_form": form, "wine": wine})



class WineDelete(LoginRequiredMixin, DeleteView):
  model = Wine
  def get_success_url(self):
    return reverse ('winery_detail', args={self.object.winery.id})


def wine_search(request):
  if request.is_ajax() and request.method == "GET":
    filter_terms = {}
    for item in request.GET.items():
      if item[1] != "" and item[0] != 'csrfmiddlewaretoken':
        if item[0] == "min_year":
          filter_terms['vintage__gte'] = item[1]
        elif item[0] == "max_year":
          filter_terms['vintage__lte'] = item[1]
        else:
          query = item[0] + "__icontains"
          filter_terms[query] = item[1]
    wines = Wine.objects.filter(**filter_terms)[:10].values('name', 'grape', 'color', 'vintage', 'id')
    wine_results = list(wines)
    colors = {}
    for c in Wine.COLOR_CHOICES:
      if c[0] != "":
        colors[c[0]] = c[1]
    for wine in wine_results:
      if wine['color'] != "":
        wine['color'] = colors[wine['color']]
      else:
        wine['color'] = ""
    return JsonResponse(wine_results,safe=False)
  return JsonResponse({}, status=400)
  


def wine_search_map(request):
  if request.is_ajax() and request.method == "GET":
    wines = Wine.objects.filter(winery__county = request.GET['county'])[:10].values('name', 'grape', 'color', 'vintage', 'id')
    wine_results = list(wines)
    colors = {}
    for c in Wine.COLOR_CHOICES:
      if c[0] != "":
        colors[c[0]] = c[1]
    for wine in wine_results:
      if wine['color'] != "":
        wine['color'] = colors[wine['color']]
      else:
        wine['color'] = ""
    return JsonResponse(wine_results, safe=False)
  return JsonResponse({}, status=400)


######## GRAPES #########


@login_required
def my_grapes(request):
  return render(request, 'mygrapes/index.html')


  
##### REGISTRATION ###########

def signup(request):
  return render(request, 'registration/signup.html')




class VintnerSignUpView(CreateView):
  model = User
  form_class = VintnerSignUpForm
  template_name = 'registration/vintner.html'
  
  def get_context_data(self, **kwargs):
    kwargs['user_type'] = 'vintner'
    return super().get_context_data(**kwargs)
  
  def form_valid(self, form):
    user = form.save()
    login(self.request, user)
    return redirect('home')




class EnthusiastSignUpView(CreateView):
    model = User
    form_class = EnthusiastSignUpForm

main_app/templates/main_app/comment_confirm_delete.html
{% extends 'base.html' %}

{% block body %}
<h1>Delete Comment</h1>

<h4>Are you sure you want to delete your comment?</span>?</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn">
  <a href="">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/comment_form.html
{% extends 'base.html' %}

{% block body %}
  
<h1>Edit</h1>
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
<!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <table>
<!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn">
</form>
{% endblock %}

main_app/templates/main_app/profile_form.html
{% extends "base.html" %}
{% block body %}
{% if user %}
<h1><span>{{ user.username }}</span></h1>
<h1><span>{{ user.first_name }}</span></h1>
<h1><span>{{ user.last_name }}</span></h1>
{% endif %}
{% endblock %}

main_app/templates/main_app/wine_confirm_delete.html
{% extends 'base.html' %}

{% block body %}
<div class="row">
  <div class="container content-container">
    <h1>Delete Wine</h1>

    <h4>Are you sure you want to delete <span style="font-style: italic;">{{ wine.name }}</span>?</h4>

    <form action="" method="POST">
      <div class="row">
        {% csrf_token %}
        <div class="col-sm-6">
          <input type="submit" value="Yes - Delete!" class="btn">
        </div>
        <div class="col-sm-6">
          <a class="btn cancel" href="{% url 'wine_detail' wine.id %}">Cancel</a>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/wine_detail.html
{% extends 'base.html' %}

{% block body %}
<div class="row">
    <div class="col content-container">
        <h2>{{wine.name}}</h2>
        <br>

        <div class="row" style="text-align: left;">
            <div class="col-sm-8">
                <p><span>produced by <a href="{% url 'winery_detail' wine.winery.id %}">{{ wine.winery.name}}</a> </span></p>
            </div>
            {% if wine.winery.user == user %}
            <div class="col-sm-1" style="margin: 0 5px;">
                <a href="{% url 'wine_update' wine.id %}">Edit</a>
            </div>

            <div class="col-sm-1" style="margin: 0 5px;">
                <a href="{% url 'wine_delete' wine.id %}">Delete</a>
            </div>
            {% endif %}
        </div>
        <br>
        <div class="divider"></div>
        <div class="row wine-attr">
            <div class="col">
                <span>Style</span>
            </div>
            <div class="col">
                <span>Grape</span>
            </div>
            <div class="col">
                <span>Vintage</span>
            </div>
            <div class="col">
                <span>Color</span>
            </div>
        </div>
        <div class="row">
            <div class="col">
                {{wine.style}}
            </div>
            <div class="col">
                {{wine.grape}}
            </div>
            <div class="col">
                {{wine.vintage}}
            </div>
            <div class="col">
                {{wine.color}}
            </div>
        </div>
        <br><br>
        <div class="row" style="text-align: left;">
            <h5>Taste Notes</h5>
        </div>
        <div class="row" style="text-align: left;">
            <p>{{ wine.taste_notes }}</p>
        </div>
        <div class="row">
            {% if wine.image_url %}
            <img src="{{ wine.image_url }}" alt="picture of wine bottle" style="width: 80%; height: auto;">
            {% endif %}
        </div>
        <br><br>

        <div class="row" style="text-align: left;">
            <h3>Other Wines at this Winery</h3>

            <div class="row" style="text-align: left;">
                {% for other_wine in wine.winery.wine_set.all %}
                {% if other_wine.id != wine.id %}
                <div style="margin-left: 15px;" class="col-sm-8">
                    <a href="{% url 'wine_detail' other_wine.id %}">
                        <span style="font-style: italic;">{{other_wine.name}} </span>
                        is a {{other_wine.vintage}} {{other_wine.style}}</a>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
        <br>

        <br>

        <div id="quini" class="row hidden" style="text-align: left;">
            <h3 id="quini-h2">Quini Reviews</h3>

            <table id="quini-list" style="text-align: left;">

            </table>
        </div>
    </div>

    <br>
    <div class="col-sm-1">
    <!--    SPACER    -->
    </div>


    <div class="col content-container">
        <h3>MySomm. Reviews</h3>
        {% for comment in wine.comment_set.all %}
        <br>
        <div class="row">
            <div class="col-sm-1"></div>
            <div class="col-sm-7">
                {{comment.content}}
            </div>
            <div class="col-sm-1"></div>
            <div class="col-sm-2">
                {{ comment.rating }} stars
            </div>
        </div>
        <br>
        <div class='row'>
            <div class="col-sm-8">
                by {%if comment.user.first_name %}
                {{ comment.user.first_name }}
                {% else %}
                {{ comment.user.username }}
                {% endif %}
            </div>
            <div class="col-sm-2">
                {% if comment.user == user %}
                <a href="{% url 'comment_delete' comment.id %}">Delete</a>
                {% endif %}
            </div>
        </div>
        <br>
           <div class="divider"></div>

        <br>
        {% endfor %}
        <div class="row">
            <form class="comment-form" action="{% url 'add_comment' wine.id %}" method="post">
                {% csrf_token %}
                {{ comment_form }}
                <br>
                <input type="submit" class="btn" value="Add Comment">
            </form>
        </div>
    </div>
</div>
<br>



<script>

    function quiniAPI(){
        const token = '{{ quini_token }}';
        const QuiniEl = document.getElementById('quini');
        const QuiniTableEl = document.getElementById('quini-list');
        let keywords = '{{ wine.name }} {{ wine.winery.name }}'
        //ajax to get wine info
        $.ajax({
            type: 'GET',
            url: 'https://quiniwine.com/api/pub/wineKeywordSearch/' + keywords + '/0/1?access_token=' + token,
            data: '',
            success: function (response) {
                if(response.items[0].Name === '{{ wine.name }}' && response.items[0].Winery === '{{wine.winery.name}}'){
                    let wineId = response.items[0].id;
                    //ajax to get info for specific wine
                    $.ajax({
                        type: 'GET',
                        url: 'https://quiniwine.com/api/pub/wineSummary.json?wine_id=' + wineId + '&access_token=' + token,
                        data: '',
                        success: function (response) {
                            QuiniEl.classList.remove('hidden');
                            let textReviews = response.agg_summary.textReviews;
                            let scores = response.aggregate.scoreAvg;
                            let eye = makeElement('Eye', textReviews.eye, scores[0]);
                            let nose = makeElement('Nose', textReviews.nose, scores[1]);
                            let mouth = makeElement('Mouth', textReviews.mouth, scores[2]);
                            let finish = makeElement('Finish', textReviews.finish, scores[3]);
                            let overall = makeElement('Overall',textReviews.overall, scores[4]);
                            QuiniTableEl.appendChild(eye);
                            QuiniTableEl.appendChild(nose);
                            QuiniTableEl.appendChild(mouth);
                            QuiniTableEl.appendChild(finish);
                            QuiniTableEl.appendChild(overall);

                        },
                        error: function (response) {
                            QuiniEl.classList.add('hidden');
                            QuiniTableEl.innerHTML = "";
                        }
                    });

                } else {
                    QuiniEl.classList.add('hidden');
                    QuiniTableEl.innerHTML = "";
                }

            },
            error: function (response) {

            }
        });

        function makeElement(category, text, score){
            let tr = document.createElement('tr');
            let catTd = document.createElement('td');
            catTd.textContent = category;
            catTd.classList.add('q-cat');
            let scoreTd = document.createElement('td');
            scoreTd.textContent = score + " / 100";
            scoreTd.classList.add('q-score');
            let textTd = document.createElement('td');
            textTd.textContent = text;
            textTd.classList.add('q-content');
            tr.appendChild(catTd);
            tr.appendChild(scoreTd);
            tr.appendChild(textTd);
            return tr;
        }
    }
    quiniAPI();
</script>


{% endblock %}

main_app/templates/main_app/wine_form.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<div class="row">
  <div class="container content-container">
    <h1>Edit {{ wine.name }}</h1>
    

    <!-- Leaving the action empty makes the form post to the same url used to display it -->
    <form action="" method="post">
      <!-- Django requires the following for security purposes -->
      {% csrf_token %}
      <table>
        <!-- Render the inputs inside of <tr>s & <td>s -->
        {{ wine_form.as_table }}
      </table>
      <input type="submit" value="Submit!" class="btn">
    </form>
  </div>
</div>
<script defer src="{% static 'js/winery.js' %}"></script>
{% endblock %}

main_app/templates/main_app/winery_confirm_delete.html
{% extends 'base.html' %}

{% block body %}
<div class="row">
  <div class="container content-container">
    <h1>Delete Winery</h1>

    <h4>Are you sure you want to delete <span class="teal-text">{{ winery.name }}</span>?</h4>
    <br>
    <form action="" method="POST">
      <div class="row">
        {% csrf_token %}
        <div class="col-sm-6">
          <input type="submit" value="Yes - Delete!" class="btn">
        </div>
        <div class="col-sm-6">
          <a class="btn cancel" href="{% url 'winery_detail' winery.id %}">Cancel</a>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/winery_form.html
{% extends 'base.html' %}

{% block body %}
<div class="row">
    <div class="container content-container">
        {% if winery %}
        <h1>Edit <span>{{ winery.name }}</span></h1>
        {% else %}
        <h1>Add Winery</h1>
        {% endif %}
        {% if error %}
        {{ error }}
        {% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
        <form action="" method="post">
<!-- Django requires the following for security purposes -->
            {% csrf_token %}
            <table>
<!-- Render the inputs inside of <tr>s & <td>s -->
                {{ form.as_table }}
            </table>
            <input type="submit" value="Submit!" class="btn">
        </form>
    </div>
</div>
{% endblock %}